name: unet
in_channels: 1
model_channels: 32
out_channels: 1
num_res_blocks: 1
attention_resolutions: []
dropout: 0
channel_mult: [1, 2, 2]
conv_resample: true
dims: 2
num_classes: null
use_checkpoint: false
num_heads: 1
num_heads_upsample: -1
use_scale_shift_norm: false