#defaults:
hydra:
  run:
    # Output directory for normal runs
    dir: ./
trainer:
  max_epochs: 100
  accumulate_grad_batches: 16
engine:
  resolution: 32
  optimizer_config:
    lr: 3e-4
  diffusion_steps: 1000
  b0: 1e-4
  bmax: 0.02
defaults:
  - model: unet
  - data: celeba
