#defaults:
hydra:
  run:
    # Output directory for normal runs
    dir: ./
trainer:
  limit_test_batches: null
run_id: g9rz03aa
use_train_data: true
seed: 0
defaults:
  - model: unet
  - data: cifar10
